# Generated by Django 3.1.1 on 2020-10-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('address', models.CharField(db_column='Address', max_length=1000, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=10, null=True)),
                ('age', models.CharField(blank=True, db_column='Age', max_length=10)),
                ('job', models.CharField(db_column='Job', default='0', max_length=100)),
                ('image', models.CharField(db_column='Image', default='0', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreateTime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdateTime')),
            ],
        ),
    ]
